[package]
name = "rinf"
version = "6.4.0"
edition = "2021"
license = "MIT"
description = "Rust for native business logic, Flutter for flexible and beautiful GUI"
repository = "https://github.com/cunarist/rinf"
documentation = "https://rinf.cunarist.com"
rust-version = "1.70"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
os-thread-local = "0.1.3"
backtrace = "0.3.69"
protoc-prebuilt = "0.2.0"
home = "0.5.9"
which = "6.0.0"
allo-isolate = "0.1.24"

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.67"
wasm-bindgen = "0.2.90"
