site_name: Rinf

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Noto Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      scheme: default
      toggle:
        icon: material/brightness-7
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.footer
  custom_dir: overrides

plugins:
  - search
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cunarist
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCJzQ3TSwHzH9dNG2L8GPDbA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cunarist

copyright: Copyright &copy; 2024 Cunarist
